//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLOYEE
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public int DepartmentId { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime DOJ { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Salary { get; set; }
        public string BankAccountNo { get; set; }
        public string ProfileImage { get; set; }
    
        public virtual TDEPARTMENT TDEPARTMENT { get; set; }
    }
}
